app:
  name: "poker-backend"
  game:
    small-blind: 5
    big-blind: 10

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
#        set debug to log Hibernate SQL statements
        SQL: info
#        set trace to log binding Hibernate parameters
        orm:
          jdbc:
            bind: info
    poker: info
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

spring:
#  main:
#    allow-bean-definition-overriding: false
  datasource:
    url: "jdbc:postgresql://${db.host}:${db.port}/${db.name}?ApplicationName=${app.name}"
    username: ${db.user}
    password: ${db.pass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        format-sql: true
    generate-ddl: true
    show-sql: true

flyway:
  user: ${db.user}
  password: ${db.pass}
  schemas: public
  url: "jdbc:postgresql://${db.host}:${db.port}/${db.name}"
#  locations: classpath:db/migration
